#!/usr/bin/env python
"""Write the public API pages used by the Meta Search design Skill.

The script renders every authoring facade from source docstrings and
signatures, then writes those pages directly to the Skill's API directory.
``pydoc-markdown`` reads source statically, so this does not import the
documented modules.

Run ``python scripts/gen_reference.py`` after changing a public facade or its
published members. Use ``--check`` to compare the current pages without
writing them.
"""

from __future__ import annotations

import ast
import re
import shutil
import subprocess
import sys
import tempfile
import threading
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from engine.generated_definitions import AUTHORING_FACADES  # noqa: E402
from aibuildai_version import RUNTIME_PACKAGES  # noqa: E402

SKILL_API_DIR = (
    REPO_ROOT
    / "plugins"
    / "aibuildai-builtin-marketplace"
    / "aibuildai-builtin"
    / "skills"
    / "meta-search-design"
    / "references"
    / "api"
)
DO_NOT_EDIT_MD = "<!-- DO NOT EDIT — generated by scripts/gen_reference.py -->\n\n"

PUBLIC_MEMBERS: dict[str, frozenset[str]] = {
    "ExecutionContext": frozenset(
        {"spawn", "wait", "cancel", "step"}
    ),
    "Handle": frozenset({"files", "result"}),
    "WaitResult": frozenset({"completed", "pending"}),
    "Search": frozenset({"explore", "budget", "delegated"}),
    "SearchBudget": frozenset({"snapshot"}),
    "BudgetSnapshot": frozenset(),
    "ExecutionBudgetSnapshot": frozenset(),
    "Agent": frozenset({"run", "execute", "verifier_invocations"}),
    "Program": frozenset({"state", "stop_requested", "scratch_dir", "artifacts_dir"}),
    "Policy": frozenset({"stop_grace_seconds", "require_gpu_use"}),
    "AgentInput": frozenset(),
    "VerifierOutput": frozenset(),
    "RolePolicy": frozenset(),
    "FileRef": frozenset({"path"}),
    "FileRoot": frozenset(),
    "SuccessfulOutput": frozenset(),
    "Failure": frozenset(),
    "FailureKind": frozenset(),
    "SearchOutput": frozenset(),
    "DeliveryRecord": frozenset(),
    "MetaAgent": frozenset(),
    "MetaAgentInput": frozenset(),
    "MetaAgentOutput": frozenset(),
}


def pydoc_markdown_bin() -> str:
    """Resolve the pydoc-markdown executable without a fixed host path."""
    found = shutil.which("pydoc-markdown")
    if found:
        return found
    fallback = Path(sys.executable).parent / "pydoc-markdown"
    assert fallback.exists(), f"pydoc-markdown not on PATH and not at {fallback}"
    return str(fallback)


def discover_modules() -> list[str]:
    """Return first-party module names so re-exported symbols can be found."""
    names: set[str] = set()
    for package in RUNTIME_PACKAGES:
        package_dir = REPO_ROOT / package
        if not package_dir.is_dir():
            raise FileNotFoundError(
                f"source package directory is missing: {package_dir}"
            )
        package_init = package_dir / "__init__.py"
        if not package_init.is_file():
            raise FileNotFoundError(
                f"source package has no __init__.py: {package_init}"
            )

        for source in package_dir.rglob("*.py"):
            relative = source.relative_to(REPO_ROOT).with_suffix("")
            if relative.parts[:3] == ("output", "web", "frontend"):
                continue
            parts = relative.parts
            if parts[-1] == "__init__":
                parts = parts[:-1]
            if not parts or any(not part.isidentifier() for part in parts):
                raise ValueError(f"source path is not a Python module name: {source}")
            names.add(".".join(parts))
    return sorted(names)


def exported_names(module_name: str) -> set[str] | None:
    """Return the names in a module's ``__all__``, or None when it has none."""
    relative = Path(*module_name.split("."))
    for candidate in (
        REPO_ROOT / relative.with_suffix(".py"),
        REPO_ROOT / relative / "__init__.py",
    ):
        if not candidate.is_file():
            continue
        for node in ast.parse(candidate.read_text(encoding="utf-8")).body:
            if not isinstance(node, ast.Assign):
                continue
            if not any(
                isinstance(target, ast.Name) and target.id == "__all__"
                for target in node.targets
            ):
                continue
            return {
                element.value
                for element in getattr(node.value, "elts", [])
                if isinstance(element, ast.Constant) and isinstance(element.value, str)
            }
    return None


_ANCHOR = re.compile(r'<a id="([^"]+)"></a>')
_TOC_LINK = re.compile(r"\(#([^)]+)\)")


def keep_only_exported(module_name: str, page: str, exported: set[str]) -> str:
    """Keep only exported facade symbols and their published members."""

    def is_public(anchor: str) -> bool:
        if not anchor.startswith(f"{module_name}."):
            return True
        parts = anchor[len(module_name) + 1 :].split(".")
        if parts[0] not in exported:
            return False
        if len(parts) == 1:
            return True
        members = PUBLIC_MEMBERS.get(parts[0])
        return members is None or parts[1] in members

    kept: list[str] = []
    dropping = False
    for block in page.split("\n\n"):
        lines = block.splitlines()
        if lines and lines[0].lstrip().startswith("*"):
            keep_lines = [
                line
                for line in lines
                if not (
                    line.lstrip().startswith("*")
                    and (match := _TOC_LINK.search(line)) is not None
                    and not is_public(match.group(1))
                )
            ]
            kept.append("\n".join(keep_lines))
            continue
        anchor = _ANCHOR.search(block)
        if anchor is not None:
            dropping = not is_public(anchor.group(1))
        if not dropping:
            kept.append(block)
    return "\n\n".join(kept)


def defining_module(name: str) -> str | None:
    """Find the first-party module that defines a re-exported symbol."""
    for module_name in discover_modules():
        relative = Path(*module_name.split("."))
        for candidate in (
            REPO_ROOT / relative.with_suffix(".py"),
            REPO_ROOT / relative / "__init__.py",
        ):
            if not candidate.is_file():
                continue
            for node in ast.parse(candidate.read_text(encoding="utf-8")).body:
                defined = isinstance(
                    node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)
                )
                if defined and node.name == name:
                    return module_name
    return None


def lift_symbol(source_module: str, page: str, facade: str, name: str) -> str:
    """Move one symbol's rendered sections from its source module to a facade."""
    taken: list[str] = []
    keeping = False
    for block in page.split("\n\n"):
        anchor = _ANCHOR.search(block)
        if anchor is not None:
            path = anchor.group(1)
            keeping = path == f"{source_module}.{name}" or path.startswith(
                f"{source_module}.{name}."
            )
        if keeping:
            taken.append(block.replace(f'"{source_module}.', f'"{facade}.'))
    return "\n\n".join(taken)


def render_missing_public_members(
    source_module: str, facade: str, name: str, existing: str
) -> str:
    """Render approved fields and properties that pydoc-markdown omits."""
    approved = PUBLIC_MEMBERS.get(name, frozenset())
    if not approved:
        return ""
    relative = Path(*source_module.split("."))
    source = next(
        path
        for path in (
            REPO_ROOT / relative.with_suffix(".py"),
            REPO_ROOT / relative / "__init__.py",
        )
        if path.is_file()
    )
    tree = ast.parse(source.read_text(encoding="utf-8"))
    class_node = next(
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == name
    )
    blocks: list[str] = []
    for node in class_node.body:
        member = getattr(node, "name", None)
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            member = node.target.id
            if member not in approved:
                continue
            declaration = f"{member}: {ast.unparse(node.annotation)}"
            if node.value is not None:
                declaration += f" = {ast.unparse(node.value)}"
            title = member
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and any(
            isinstance(decorator, ast.Name) and decorator.id == "property"
            for decorator in node.decorator_list
        ):
            if member not in approved:
                continue
            returns = ast.unparse(node.returns) if node.returns is not None else "Any"
            declaration = f"@property\ndef {member}() -> {returns}"
            title = member
        else:
            continue
        anchor = f"{facade}.{name}.{member}"
        if f'<a id="{anchor}"></a>' in existing:
            continue
        doc = ast.get_docstring(node) if isinstance(node, ast.FunctionDef) else None
        block = (
            f'<a id="{anchor}"></a>\n\n#### {title}\n\n```python\n{declaration}\n```'
        )
        if doc:
            block += f"\n\n{doc}"
        blocks.append(block)
    return "\n\n".join(blocks)


_HEADING = re.compile(r"^(#{1,6}) (.+)$")


def rebuild_toc(page: str) -> str:
    """Build the table of contents from the finished facade page."""
    blocks = page.split("\n\n")
    entries: list[str] = []
    anchor: str | None = None
    for block in blocks:
        found = _ANCHOR.search(block)
        if found is not None:
            anchor = found.group(1)
            continue
        heading = _HEADING.match(block.strip())
        if heading is None or anchor is None:
            continue
        depth = len(heading.group(1))
        title = heading.group(2).removesuffix(" Objects")
        entries.append(f"{'  ' * max(0, depth - 1)}* [{title}](#{anchor})")
        anchor = None
    toc = "# Table of Contents\n\n" + "\n".join(entries)

    def is_old_toc(block: str) -> bool:
        lines = [line for line in block.splitlines() if line.strip()]
        return block.startswith("# Table of Contents") or (
            bool(lines)
            and all(
                line.lstrip().startswith("*") and _TOC_LINK.search(line) is not None
                for line in lines
            )
        )

    body = [block for block in blocks if not is_old_toc(block)]
    return "\n\n".join([toc, *body])


_RENDERED: dict[str, str] = {}
_MODULE_LOCKS: dict[str, threading.Lock] = {}
_REGISTRY_LOCK = threading.Lock()


def render_module(module_name: str, bin_path: str) -> str:
    """Render one module with pydoc-markdown, once per process.

    Every pydoc-markdown call is one interpreter start of about a second, and
    a source module is asked for by every facade that lifts a symbol from it,
    so the rendered page is kept by module name. One lock per module makes the
    facades' parallel renders wait for the first render of a shared module
    instead of each starting their own."""
    with _REGISTRY_LOCK:
        lock = _MODULE_LOCKS.setdefault(module_name, threading.Lock())
    with lock:
        if module_name not in _RENDERED:
            _RENDERED[module_name] = subprocess.run(
                [bin_path, "-m", module_name, "-I", str(REPO_ROOT), "--render-toc"],
                capture_output=True,
                text=True,
                check=True,
            ).stdout
        return _RENDERED[module_name]


def render_facade(module_name: str, bin_path: str) -> str:
    """Render one public facade and its approved re-exported symbols."""
    page = render_module(module_name, bin_path)
    exported = exported_names(module_name)
    if exported is None:
        raise AssertionError(f"public facade {module_name} declares no __all__")
    page = keep_only_exported(module_name, page, exported)
    for name in sorted(exported):
        if f'<a id="{module_name}.{name}"></a>' in page:
            continue
        source = defining_module(name)
        if source is None:
            raise AssertionError(
                f"{module_name} exports {name}, which is defined nowhere"
            )
        source_page = render_module(source, bin_path)
        lifted = lift_symbol(source, source_page, module_name, name)
        if not lifted:
            raise AssertionError(f"{name} has no rendered section in {source}")
        missing_members = render_missing_public_members(
            source, module_name, name, lifted
        )
        if missing_members:
            lifted = lifted.rstrip() + "\n\n" + missing_members
        page = page.rstrip() + "\n\n" + lifted + "\n"
    return rebuild_toc(keep_only_exported(module_name, page, exported))


def build_api(output_dir: Path) -> int:
    """Build one Skill API page per authoring facade in a temporary directory."""
    output_dir.mkdir(parents=True, exist_ok=True)
    bin_path = pydoc_markdown_bin()
    # The facades are independent pages, so they render at once; the shared
    # module cache keeps a source module at one pydoc-markdown call.
    with ThreadPoolExecutor(max_workers=8) as renderers:
        pages = list(
            renderers.map(lambda facade: render_facade(facade, bin_path), AUTHORING_FACADES)
        )
    for facade, markdown in zip(AUTHORING_FACADES, pages, strict=True):
        (output_dir / f"{facade}.md").write_text(
            DO_NOT_EDIT_MD + markdown.rstrip() + "\n",
            encoding="utf-8",
        )
    return len(AUTHORING_FACADES)


def replace_api() -> int:
    """Replace the Skill API directory after every page renders."""
    SKILL_API_DIR.parent.mkdir(parents=True, exist_ok=True)
    backup_dir = SKILL_API_DIR.with_name(f".{SKILL_API_DIR.name}.backup")
    if backup_dir.exists():
        raise FileExistsError(f"API output backup already exists: {backup_dir}")

    with tempfile.TemporaryDirectory(
        dir=SKILL_API_DIR.parent,
        prefix=f".{SKILL_API_DIR.name}.",
    ) as temp_root:
        built_dir = Path(temp_root) / SKILL_API_DIR.name
        count = build_api(built_dir)
        if SKILL_API_DIR.exists():
            SKILL_API_DIR.rename(backup_dir)
            try:
                built_dir.rename(SKILL_API_DIR)
            except OSError:
                backup_dir.rename(SKILL_API_DIR)
                raise
            shutil.rmtree(backup_dir)
        else:
            built_dir.rename(SKILL_API_DIR)
    return count


def check_target(expected_dir: Path, actual_dir: Path) -> list[str]:
    """Return byte differences between expected and current API pages."""
    expected_files = {
        path.relative_to(expected_dir)
        for path in expected_dir.rglob("*")
        if path.is_file()
    }
    actual_files = (
        {
            path.relative_to(actual_dir)
            for path in actual_dir.rglob("*")
            if path.is_file()
        }
        if actual_dir.is_dir()
        else set()
    )
    stale: list[str] = []
    stale.extend(f"missing {path}" for path in sorted(expected_files - actual_files))
    stale.extend(f"extra {path}" for path in sorted(actual_files - expected_files))
    stale.extend(
        f"stale {path}"
        for path in sorted(expected_files & actual_files)
        if (expected_dir / path).read_bytes() != (actual_dir / path).read_bytes()
    )
    return stale


def check_api() -> None:
    """Render temporary pages and compare them with the committed pages."""
    with tempfile.TemporaryDirectory(prefix="gen-ref-check-") as tmp:
        expected_dir = Path(tmp) / "api"
        build_api(expected_dir)
        stale = check_target(expected_dir, SKILL_API_DIR)
    if stale:
        print("public API pages are stale:", file=sys.stderr)
        for item in stale:
            print(f"  {item}", file=sys.stderr)
        raise SystemExit(1)
    print(f"{len(AUTHORING_FACADES)} public API pages are up to date")


def main() -> None:
    if "--check" in sys.argv[1:]:
        check_api()
        return
    count = replace_api()
    print(f"synced {count} public API pages to {SKILL_API_DIR.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
