/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/actions/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Run */
        post: operations["pause_run_api_v1_runs__run_id__actions_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/actions/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Run */
        post: operations["resume_run_api_v1_runs__run_id__actions_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Capabilities
         * @description The server-decided action surface: the frontend renders these and invents no lifecycle policy of its own.
         */
        get: operations["run_capabilities_api_v1_runs__run_id__capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/execution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution */
        get: operations["execution_api_v1_runs__run_id__execution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_runs__run_id__metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/resources/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource History */
        get: operations["resource_history_api_v1_runs__run_id__resources_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run */
        get: operations["run_api_v1_runs__run_id__run_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transcript */
        get: operations["transcript_api_v1_runs__run_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workspace/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Download */
        get: operations["workspace_download_api_v1_runs__run_id__workspace_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workspace/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Entries */
        get: operations["workspace_entries_api_v1_runs__run_id__workspace_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workspace/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Raw */
        get: operations["workspace_raw_api_v1_runs__run_id__workspace_raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workspace/stat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Stat */
        get: operations["workspace_stat_api_v1_runs__run_id__workspace_stat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/workspace/text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace Text */
        get: operations["workspace_text_api_v1_runs__run_id__workspace_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Resources */
        get: operations["system_resources_api_v1_system_resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/theme.css": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Theme */
        get: operations["theme_api_v1_theme_css_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CsrfResponse
         * @description The service's per-start CSRF token. Mutation routes require it back in the ``X-AIBuildAI-Csrf`` header; a cross-site page cannot read this response, so it cannot mutate.
         */
        CsrfResponse: {
            /** Token */
            token: string;
        };
        /**
         * ExecutionDetailResponse
         * @description One execution's readable detail for the Inspector.
         */
        ExecutionDetailResponse: {
            /** Child Paths */
            child_paths: string[];
            /** Facts */
            facts: components["schemas"]["FactRow"][];
            /** Failure Summary */
            failure_summary: string | null;
            /** Input Summary */
            input_summary: string | null;
            /** Metric Components */
            metric_components: components["schemas"]["MetricComponent"][];
            /** Output Summary */
            output_summary: string | null;
            summary: components["schemas"]["ExecutionSummary"];
            /** Workspace Path */
            workspace_path: string;
        };
        /**
         * ExecutionSummary
         * @description One execution summary for the Execution Atlas and run overview.
         */
        ExecutionSummary: {
            /** Action Method */
            action_method: string | null;
            /** Action Ordinal */
            action_ordinal: number;
            /** Budget S */
            budget_s?: number | null;
            /** Child Count */
            child_count: number;
            /** Cost */
            cost: number | null;
            /** Elapsed S */
            elapsed_s: number | null;
            /**
             * Family
             * @enum {string}
             */
            family: "search" | "composite" | "agent" | "program" | "work_unit" | "execution";
            /** Identity Path */
            identity_path: string;
            /** Label */
            label: string;
            /** Metric */
            metric: number | null;
            /** Model */
            model?: string | null;
            /** Parent Path */
            parent_path: string | null;
            /** Path */
            path: string;
            score: components["schemas"]["ScoredExecution"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Status Style Token */
            status_style_token: string;
            /** Status Symbol */
            status_symbol: string;
            /** Status Word */
            status_word: string;
            /** Transcript Available */
            transcript_available: boolean;
            /** Upstream Actions */
            upstream_actions: string[];
        };
        /**
         * FactRow
         * @description One family-specific detail fact, already rendered as label and text.
         */
        FactRow: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /**
         * FoldBlock
         * @description A time-stamped folded block: thinking, a tool result, a warning, a budget note. ``tag`` is the bracket tag the transcript writes (``thinking``, ``INFO``, ``WARN``, ``BUDGET``), ``title`` its summary words, ``meta`` the size note (``text, 25 lines``).
         */
        FoldBlock: {
            /** Code */
            code: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fold";
            /** Lang */
            lang: string;
            /** Meta */
            meta: string;
            /** Tag */
            tag: string;
            /** Title */
            title: string;
            /** Ts */
            ts: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetricComponent
         * @description One named component of a recorded metric.
         */
        MetricComponent: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /**
         * MetricSeries
         * @description One metric's recorded curve from metrics.jsonl.
         *
         *     A typed projection of the recorded metric data. It contains semantic
         *     series, never chart configuration: the frontend owns how a series
         *     becomes a chart. ``segment`` is the 1-based series segment (one per
         *     ``aibuildai.init()``), ``x_kind`` names the x axis the recorded data
         *     supports (epoch when strictly increasing, else step).
         */
        MetricSeries: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Segment */
            segment: number;
            /**
             * X Kind
             * @enum {string}
             */
            x_kind: "epoch" | "step";
            /** Xs */
            xs: number[];
            /** Ys */
            ys: number[];
        };
        /**
         * MetricSeriesResponse
         * @description The recorded metric curves for one WorkUnit execution.
         *
         *     ``series`` is empty when the unit recorded no metrics (the honest
         *     empty state) — nothing is fabricated for display.
         */
        MetricSeriesResponse: {
            /** Path */
            path: string;
            /** Series */
            series: components["schemas"]["MetricSeries"][];
        };
        /**
         * OtherBlock
         * @description Any transcript chunk the typed blocks do not name (sub-agent dispatch, hook text, the step result table): rendered as Markdown.
         */
        OtherBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "other";
            /** Markdown */
            markdown: string;
        };
        /**
         * RunActionFailure
         * @description The user operation that failed and its safe display message.
         */
        RunActionFailure: {
            /** Error */
            error: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pause" | "resume";
        };
        /**
         * RunCapabilitiesResponse
         * @description The server-decided action surface and temporary per-Run operation.
         */
        RunCapabilitiesResponse: {
            control: components["schemas"]["RunControl"] | null;
            failure: components["schemas"]["RunActionFailure"] | null;
        };
        /**
         * RunControl
         * @description The one Run control the server tells Web to render, if any.
         */
        RunControl: {
            /** Enabled */
            enabled: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pause" | "resume";
            /** Pending */
            pending: boolean;
            /** Reason */
            reason: string | null;
        };
        /**
         * RunResponse
         * @description The polled run surface: run-level facts plus the flat execution list.
         */
        RunResponse: {
            /** Active Execution Count */
            active_execution_count: number;
            /** Cost Budget Usd */
            cost_budget_usd: number | null;
            /** Cost Is Estimate */
            cost_is_estimate: boolean;
            /** Elapsed S */
            elapsed_s: number;
            /** Executions */
            executions: components["schemas"]["ExecutionSummary"][];
            /** Frame Elapsed S */
            frame_elapsed_s: number;
            /** Frame Revision */
            frame_revision: number;
            /** Generated At Unix */
            generated_at_unix: number;
            /** Head Elapsed S */
            head_elapsed_s: number;
            /** Head Revision */
            head_revision: number;
            /**
             * Metric Direction
             * @enum {string}
             */
            metric_direction: "max" | "min";
            /** Metric Name */
            metric_name: string;
            /** Model */
            model: string;
            /** Remaining S */
            remaining_s: number | null;
            /** Result Recorded */
            result_recorded: boolean;
            /** Run Id */
            run_id: string;
            /** Selected Metric */
            selected_metric: number | null;
            /** Selected Result Path */
            selected_result_path: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "failed";
            /** Status Style Token */
            status_style_token: string;
            /** Status Symbol */
            status_symbol: string;
            /** Status Word */
            status_word: string;
            /** Task Name */
            task_name: string;
            /** Total Cost */
            total_cost: number;
            /** View Age S */
            view_age_s: number;
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["RunWarningRow"][];
            /** Warnings Count */
            warnings_count: number;
        };
        /**
         * RunSummary
         * @description One indexed run's row for the global run selector and the Workspace home page.
         *
         *     Orthogonal authoritative facts, never a lifecycle state machine:
         *     ``active`` says the run has a process owner right now (its systemd
         *     unit or live member), ``result`` is the journal's explicit final
         *     Search result, ``incompatible`` says this build cannot restore the
         *     records, and ``availability`` says whether its projection is ready.
         *     ``status_word`` and ``status_style_token`` are derived presentation
         *     only; no policy reads them back. The optional facts are filled only
         *     when they are cheap: the final config for the model, and a member's
         *     summary when one is connected.
         */
        RunSummary: {
            /** Active */
            active: boolean;
            /**
             * Availability
             * @enum {string}
             */
            availability: "ready" | "restoring" | "unavailable";
            /** Diagnostic */
            diagnostic: string | null;
            /** Elapsed S */
            elapsed_s: number | null;
            /** Ended At Unix */
            ended_at_unix: number | null;
            /** Incompatible */
            incompatible: boolean;
            /** Metric Name */
            metric_name: string | null;
            /** Model */
            model: string | null;
            /** Result */
            result: ("completed" | "failed") | null;
            /** Run Id */
            run_id: string;
            /** Selected Metric */
            selected_metric: number | null;
            /** Started At Unix */
            started_at_unix: number | null;
            /** Status Style Token */
            status_style_token: string;
            /** Status Word */
            status_word: string;
            /** Task Name */
            task_name: string;
            /** Updated At Unix */
            updated_at_unix: number | null;
        };
        /**
         * RunWarningRow
         * @description One run-level downgrade as the display reads it.
         *
         *     Typed rather than a loose mapping, so the generated frontend types name
         *     these four fields and a renderer that reads a fifth fails to compile.
         */
        RunWarningRow: {
            /** At S */
            at_s: number;
            /** Category */
            category: string;
            /** Message */
            message: string;
            /** Source */
            source: string;
        };
        /**
         * RunsResponse
         * @description Every indexed run, sorted for the selector: running first by latest update, then resumable, then ended runs by end time; ``run_id`` breaks ties.
         */
        RunsResponse: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * ScoredExecution
         * @description The score one execution's own Output carries.
         */
        ScoredExecution: {
            /** Metric Components */
            metric_components: components["schemas"]["MetricComponent"][];
            /** Score */
            score: number;
        };
        /**
         * TextBlock
         * @description Agent prose. ``source`` is ``parent`` or a sub-agent name; ``markdown`` is the prose as written.
         */
        TextBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Markdown */
            markdown: string;
            /** Source */
            source: string;
            /** Ts */
            ts: string;
        };
        /**
         * ToolCallBlock
         * @description One tool call with its input (Markdown, as the transcript renders that tool's input), the tool's note line when the input carried one, and the result that answered it, when it has arrived.
         */
        ToolCallBlock: {
            /** Input Markdown */
            input_markdown: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "tool_call";
            /** Name */
            name: string;
            /** Note */
            note: string | null;
            result: components["schemas"]["FoldBlock"] | null;
            /** Ts */
            ts: string;
        };
        /**
         * TranscriptResponse
         * @description The Agent transcript read back from its written Markdown into turns of typed blocks. ``header_markdown`` is everything before the first turn (the session header).
         */
        TranscriptResponse: {
            /** Header Markdown */
            header_markdown: string;
            /** Path */
            path: string;
            /** Terminal */
            terminal: boolean;
            /** Turns */
            turns: components["schemas"]["TranscriptTurn"][];
        };
        /**
         * TranscriptTurn
         * @description One assistant turn. ``start_ts`` is the first stamped block's elapsed time; ``duration_s`` the span to the last one; ``tokens_in``/``tokens_out`` the context line's counts, when the turn has closed.
         */
        TranscriptTurn: {
            /** Blocks */
            blocks: (components["schemas"]["FoldBlock"] | components["schemas"]["TextBlock"] | components["schemas"]["ToolCallBlock"] | components["schemas"]["OtherBlock"])[];
            /** Duration S */
            duration_s: number | null;
            /** Index */
            index: number;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /** Start Ts */
            start_ts: string | null;
            /** Tokens In */
            tokens_in: string | null;
            /** Tokens Out */
            tokens_out: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkspaceEntriesResponse
         * @description The direct children of one directory, directories first; ``truncated`` says the listing was cut at the entry limit.
         */
        WorkspaceEntriesResponse: {
            /** Entries */
            entries: components["schemas"]["WorkspaceEntry"][];
            /** Path */
            path: string;
            /** Truncated */
            truncated: boolean;
        };
        /**
         * WorkspaceEntry
         * @description One entry of the run's workspace tree. ``path`` is workspace-relative POSIX; the host path never leaves the member. ``preview_kind`` is the one classifier: the browser picks its renderer from it and keeps no extension table of its own.
         */
        WorkspaceEntry: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "directory" | "file" | "symlink" | "other";
            /** Language */
            language: string | null;
            /** Mime Type */
            mime_type: string | null;
            /** Modified At Unix */
            modified_at_unix: number | null;
            /** Name */
            name: string;
            /** Path */
            path: string;
            /**
             * Preview Kind
             * @enum {string}
             */
            preview_kind: "code" | "text" | "markdown" | "pdf" | "image" | "download_only" | "unavailable";
            /** Size */
            size: number | null;
        };
        /**
         * WorkspaceHealth
         * @description The named backend identity at ``/api/v1/health``. The deployment controller reads it before Caddy promotes a generation; the frontend reads ``ready`` only.
         */
        WorkspaceHealth: {
            /** App Version */
            app_version: string;
            /** Member Protocol Version */
            member_protocol_version: number;
            /**
             * Ready
             * @constant
             */
            ready: true;
            /** Web Build Id */
            web_build_id: string;
            /** Web Protocol Version */
            web_protocol_version: number;
            /** Workspace Name */
            workspace_name: string;
        };
        /**
         * WorkspaceStatResponse
         * @description One entry's metadata and its revision identity (the ETag the byte routes also send).
         */
        WorkspaceStatResponse: {
            entry: components["schemas"]["WorkspaceEntry"];
            /** Etag */
            etag: string;
        };
        /**
         * WorkspaceTextResponse
         * @description The first bytes of one regular file as text. ``truncated`` means only the initial portion up to the preview limit is here; ``size`` is the whole file.
         */
        WorkspaceTextResponse: {
            /** Encoding */
            encoding: string;
            /** Etag */
            etag: string;
            /** Language */
            language: string | null;
            /** Path */
            path: string;
            /** Returned Bytes */
            returned_bytes: number;
            /** Size */
            size: number;
            /** Text */
            text: string;
            /** Truncated */
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    csrf_api_v1_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceHealth"];
                };
            };
        };
    };
    runs_api_v1_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
        };
    };
    pause_run_api_v1_runs__run_id__actions_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_run_api_v1_runs__run_id__actions_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_capabilities_api_v1_runs__run_id__capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCapabilitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_api_v1_runs__run_id__execution_get: {
        parameters: {
            query: {
                path: string;
                revision?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_runs__run_id__metrics_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resource_history_api_v1_runs__run_id__resources_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_v1_runs__run_id__run_get: {
        parameters: {
            query?: {
                at_s?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transcript_api_v1_runs__run_id__transcript_get: {
        parameters: {
            query: {
                path: string;
                revision?: number | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_download_api_v1_runs__run_id__workspace_download_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_entries_api_v1_runs__run_id__workspace_entries_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceEntriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_raw_api_v1_runs__run_id__workspace_raw_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_stat_api_v1_runs__run_id__workspace_stat_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceStatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_text_api_v1_runs__run_id__workspace_text_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_resources_api_v1_system_resources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    theme_api_v1_theme_css_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
